# Generated by Django 4.2.3 on 2023-08-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeNo', models.CharField(default='', max_length=10)),
                ('street', models.CharField(default='', max_length=70)),
                ('postCode', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=70)),
                ('country', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
